### PR TITLE
Added missing method example

### PR DESCRIPTION
**Pull request by ghost**
echo $entry->getPath() . "<br />";

### CODE REVIEW

**Comment by Gemorroj** [comment]
I think this level of detail, especially with the "<br/>", not needed in the base case.

**Comment by ghost** [comment]
Because without the example of 
`echo $entry->getPath() . "<br />";`
the class doesn't actually do anything useful which can be used elsewhere. It merely dumps out some info as a var_dump.
It took me a long while to work out how to use this without any documentation or examples.
A new user should not have to work out what methods exist within a class, so I provided this example so other people could use the class.

**Comment by Gemorroj** [comment]
I think this helps b95b35b376d1d2c876e2c0ec21282088ae4c183b

**Comment by ghost** [comment]
Hey, that looks really good. Thanks!

**Pull request closed without merging**
